//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cvoya.Graph.Model.Analyzers.Properties;

using System;

#nullable enable
/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources
{
    private static global::System.Resources.ResourceManager? resourceMan;

    private static global::System.Globalization.CultureInfo? resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (resourceMan is null)
            {
                var temp = new global::System.Resources.ResourceManager("Cvoya.Graph.Model.Analyzers.Properties.Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    /// <summary>
    ///   Looks up a localized string similar to INode and IRelationship can only be implemented by classes, not structs..
    /// </summary>
    internal static string GM001_Description => ResourceManager.GetString("GM001_Description", resourceCulture)!;

    /// <summary>
    ///   Looks up a localized string similar to Struct '{0}' cannot implement {1}. Only classes are supported..
    /// </summary>
    internal static string GM001_MessageFormat => ResourceManager.GetString("GM001_MessageFormat", resourceCulture)!;

    /// <summary>
    ///   Looks up a localized string similar to Structs cannot implement INode or IRelationship.
    /// </summary>
    internal static string GM001_Title => ResourceManager.GetString("GM001_Title", resourceCulture)!;

    /// <summary>
    ///   Looks up a localized string similar to Types implementing INode or IRelationship must have a parameterless constructor..
    /// </summary>
    internal static string GM002_Description => ResourceManager.GetString("GM002_Description", resourceCulture)!;

    /// <summary>
    ///   Looks up a localized string similar to Type '{0}' must have a parameterless constructor (public or internal)..
    /// </summary>
    internal static string GM002_MessageFormat => ResourceManager.GetString("GM002_MessageFormat", resourceCulture)!;

    /// <summary>
    ///   Looks up a localized string similar to Missing parameterless constructor.
    /// </summary>
    internal static string GM002_Title => ResourceManager.GetString("GM002_Title", resourceCulture)!;

    /// <summary>
    ///   Looks up a localized string similar to All properties in INode and IRelationship implementations must have public getters and setters..
    /// </summary>
    internal static string GM003_Description => ResourceManager.GetString("GM003_Description", resourceCulture)!;

    /// <summary>
    ///   Looks up a localized string similar to Property '{0}' must have public getter and setter..
    /// </summary>
    internal static string GM003_MessageFormat => ResourceManager.GetString("GM003_MessageFormat", resourceCulture)!;

    /// <summary>
    ///   Looks up a localized string similar to Property must have public getter and setter.
    /// </summary>
    internal static string GM003_Title => ResourceManager.GetString("GM003_Title", resourceCulture)!;

    /// <summary>
    ///   Looks up a localized string similar to Properties of this type are not supported in graph entities..
    /// </summary>
    internal static string GM004_Description => ResourceManager.GetString("GM004_Description", resourceCulture)!;

    /// <summary>
    ///   Looks up a localized string similar to Property '{0}' has unsupported type '{1}'..
    /// </summary>
    internal static string GM004_MessageFormat => ResourceManager.GetString("GM004_MessageFormat", resourceCulture)!;

    /// <summary>
    ///   Looks up a localized string similar to Unsupported property type.
    /// </summary>
    internal static string GM004_Title => ResourceManager.GetString("GM004_Title", resourceCulture)!;

    /// <summary>
    ///   Looks up a localized string similar to Complex type properties can only be used in INode implementations, not IRelationship..
    /// </summary>
    internal static string GM005_Description => ResourceManager.GetString("GM005_Description", resourceCulture)!;

    /// <summary>
    ///   Looks up a localized string similar to Property '{0}' with complex type '{1}' cannot be used in IRelationship implementations..
    /// </summary>
    internal static string GM005_MessageFormat => ResourceManager.GetString("GM005_MessageFormat", resourceCulture)!;

    /// <summary>
    ///   Looks up a localized string similar to Complex type properties not allowed in IRelationship.
    /// </summary>
    internal static string GM005_Title => ResourceManager.GetString("GM005_Title", resourceCulture)!;
}