name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '10.0.x'
    
    - name: Start Neo4j
      run: scripts/containers/start-neo4j.sh

    - name: Restore dependencies
      run: dotnet restore
      working-directory: .
    
    - name: Set up local feed
      run: dotnet build --configuration LocalFeed --no-restore
      working-directory: .

    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: .
    
    - name: Test Analyzers
      run: dotnet test --project tests/Graph.Model.Analyzers.Tests/Graph.Model.Analyzers.Tests.csproj --no-build --configuration Release --verbosity normal
      
    - name: Test Neo4j Provider
      env:
        USE_NEO4J_CONTAINERS: true
      run: dotnet test --project tests/Graph.Model.Neo4j.Tests/Graph.Model.Neo4j.Tests.csproj --no-build --configuration Release --verbosity normal
