name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '10.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: .
    
    - name: Set up local feed
      run: dotnet build --configuration LocalFeed --no-restore
      working-directory: .

    - name: Build
      run: dotnet build --no-restore --configuration Release -p:UseProjectReferences=false
      working-directory: .
    
    - name: Test Analyzers
      run: dotnet test tests/Graph.Model.Analyzers.Tests --no-build --verbosity normal --collect:"XPlat Code Coverage"
      
    - name: Test Neo4j Provider with Docker containers
      env:
        USE_NEO4J_CONTAINERS: true
      run: dotnet test tests/Graph.Model.Neo4j.Tests --no-build --verbosity normal --collect:"XPlat Code Coverage"